baseURL = "/"
title = "新疆应急法规汇编"
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
theme = "hugo-book"
keywords = ["应急法规", "应急法规汇编", "新疆应急", "安全生产法规", "应急管理法规", "新疆应急管理厅", "新疆维吾尔自治区应急管理厅"]
# enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'

  BookSearch = true
  BookComments = false
  BookFlatSection = true
  enableInlineShortcodes = true
  localSearch = true
  description = "新疆维吾尔自治区应急管理厅官方打造的应急法规汇编，包含安全生产、应急救援、防灾减灾等方面常见的法律、法规、规范性文件，是应急人必备的法规查询工具。"
  keywords = ["应急法规", "应急法规汇编", "新疆应急", "安全生产法规", "应急管理法规", "新疆应急管理厅", "新疆维吾尔自治区应急管理厅"]
  [markup]
  [markup.tableOfContents]
    # 纳入目录的最小标题级别，默认为3
    endLevel = 4
    # 是否排序，其实就是是否在目录的前面添加序号“1. ”、"2. "等等
    ordered = false
    # 纳入目录的最大标题级别，默认为2
    startLevel = 2